core/permits/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, FloatField, RadioField, SelectField
from wtforms.validators import DataRequired, Length, InputRequired, NumberRange

from core.models import Permit

LOCATION = [('bwd', 'BWD'), ('hnd', 'HND'), ('cch', 'CCH'), ('syo', 'SYO')]
CHOICES = [('yes', 'Yes'), ('no', 'No')]


class PermitForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=3, message='Title is too short')])
    text = TextAreaField('Findings', validators=[DataRequired(), Length(min=2, message='Description is too short')])
    location = SelectField('Location', choices=LOCATION, default=0)
    mileage = FloatField('Mileage', validators=[InputRequired(message='Please put a mileage'),
                                                            NumberRange(min=1, message='Value must be 1 or above')])
    resolved = RadioField('Was resolved?', choices=CHOICES, validators=[InputRequired()], default=('yes'))
    follow_up = RadioField('Follow Up required?', choices=CHOICES, validators=[InputRequired()], default=('yes'))
    submit = SubmitField('Submit')

core/accounts/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from flask_login import login_user, logout_user, current_user, login_required

from core import db
from core.models import User, Permit
from core.accounts.forms import LoginForm, RegistrationForm, UpdateUserForm

accounts = Blueprint('accounts', __name__)


@accounts.route('/logout')
def logout():
    logout_user()
    flash('You have been logged out')
    return redirect(url_for('permit.index'))


@accounts.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Registration successful')
        return redirect(url_for('accounts.login'))
    return render_template('register.html', title='Register the account', form=form)


@accounts.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first_or_404()
        if user.check_password(form.password.data) and user is not None:
            login_user(user, remember=True)
            flash('Welcome ' + current_user.username.capitalize())
            next = request.args.get('next')
            return redirect(url_for('permit.index') or next)
        flash('Invalid username/password')
        return redirect(url_for('accounts.login'))

    return render_template('login.html', title='Log-in form', form=form)


@accounts.route('/update', methods=['GET', 'POST'])
@login_required
def update():
    form = UpdateUserForm()

    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Updated successfuly')
        return redirect(url_for('accounts.update'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('update.html', title=current_user.username.capitalize(), form=form)


@accounts.route('/<username>')
def user_permits(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    permits = Permit.query.filter_by(author=user).order_by(Permit.date.desc()).paginate(page=page, per_page=5)
    flash('List of permits submited by ' + username)

    return render_template('user_permits.html', title='User permit', permits=permits, user=user)

core/permits/views.py
from flask import render_template, redirect, request, url_for, Blueprint, flash, abort
from jinja2 import TemplateNotFound

from flask_login import current_user, login_required

from core import db
from core.models import Permit
from core.permits.forms import PermitForm

permits = Blueprint('permit', __name__)


@permits.route('/')
def index():
    try:
        return render_template('index.html', title='Permit Log')
    except TemplateNotFound:
        abort(404)


@permits.route('/create_permit', methods=['GET', 'POST'])
@login_required
def create_permit():
    form = PermitForm()

    if form.validate_on_submit():
        permit = Permit(user_id=current_user.id,
                        title=form.title.data,
                        text=form.text.data,
                        location=form.location.data,
                        mileage=form.mileage.data,
                        resolved=form.resolved.data,
                        follow_up=form.follow_up.data)
        db.session.add(permit)
        db.session.commit()
        flash('Posted Successfuly')
        return redirect(url_for('permit.permit_list'))
    return render_template('create_permit.html', title='Create Permit', form=form)


@permits.route('/<int:permit_id>')
@login_required
def permit(permit_id):
    permit = Permit.query.get_or_404(permit_id)
    return render_template('permit.html', title=permit.title, date=permit.date, permit=permit)


@permits.route('/<int:permit_id>/update', methods=['GET', 'POST'])
@login_required
def update_permit(permit_id):
    permit = Permit.query.get_or_404(permit_id)
    if permit.author != current_user:
        abort(403)

    form = PermitForm()
    if form.validate_on_submit():
        permit.title = form.title.data
        permit.text = form.text.data
        permit.location = form.location.data
        permit.mileage = form.mileage.data
        permit.resolved = form.resolved.data
        permit.follow_up = form.follow_up.data
        db.session.commit()
        flash('Updated Successfuly')
        return redirect(url_for('permit.permit', permit_id=permit.id))

    elif request.method == 'GET':
        form.title.data = permit.title
        form.text.data = permit.text
        form.location.data = permit.location
        form.mileage.data = permit.mileage
        form.resolved.data = permit.resolved
        form.follow_up.data = permit.follow_up

    return render_template('create_permit.html', title='Update Permit', form=form)


@permits.route('/<int:permit_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_permit(permit_id):
    permit = Permit.query.get_or_404(permit_id)
    if permit.author != current_user:
        abort(403)

    db.session.delete(permit)
    db.session.commit()
    flash('Permit Deleted')
    return redirect(url_for('permit.permit_list'))


@permits.route('/permit_list')
@login_required
def permit_list():
    page = request.args.get('page', 1, type=int)
    permits = Permit.query.order_by(Permit.date.desc()).paginate(page=page, per_page=5)
    return render_template('permit_list.html', title='Permits List', permits=permits)

core/templates/_render_field.html
{% macro render_field(field) %}
    {{ field.label(class='label-class') }}
    {{ field(**kwargs)|safe }}

    {% for error in field.errors %}
        <p class="error-class">{{ error }}</p>
    {% endfor %}
{% endmacro %}

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ title }}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" type="text/css" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-customized">

            <ul class="navbar-nav">
                <li class="nav-item active"><a class="nav-link" href="{{ url_for('permit.index') }}">Home</a></li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{{url_for('permit.create_permit') }}">Create Post</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{url_for('permit.permit_list') }}">All Permits</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('accounts.update') }}">Account</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('accounts.logout') }}">Log-out</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('accounts.login') }}">Log In</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('accounts.register') }}">Register</a></li>
                {% endif %}
            </ul>
                {% for message in get_flashed_messages() %}
                    <div>
                        {{ message }}
                    </div>
                {% endfor %}

    </nav>

    <div class="container-fluid main-gradient">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

<!--1. Search-->
<!--2. Pdf-->
<!--3. Context on Youtube-->
<!--soc icons-->

core/templates/create_permit.html
{% extends 'base.html' %}

{% block content %}
<div class="form-div d-flex justify-content-center col-md-6">
    <form method="POST">
        <div class="form-group">
        {{ form.hidden_tag() }}
            <div class="form-group row">
                <h4>Please fill in the form:</h4>
            </div>
            <div class="form-group row">
                {{ form.title.label(class='label-class') }}
                {{ form.title(class='form-control', placeholder='Enter Title') }}
            </div>
            <div class="form-group row">
                {{ form.text.label(class='label-class') }}
                {{ form.text(class='form-control', placeholder='Short Description', rows=4) }}
            </div>
            <div class="form-group row">
                {{ form.mileage.label(class='label-class') }}
                {{ form.mileage(class='form-control', placeholder='Miles Covered', type='number') }}
            </div>
            <div class="form-group row">
                {{ form.location.label(class='label-class') }} {{ form.location(class='form-control') }}
            </div>
            <div class="form-group row">
                {{ form.resolved.label(class='label-class') }}
                {{ form.resolved(class='radio-class', checked='Yes') }}
                {{ form.follow_up.label(class='label-class radio-class2') }}
                {{ form.follow_up(class='radio-class') }}
            </div>
            <div class="form-group row">
                {{ form.submit(class='btn-customized btn btn-success') }}
            </div>
            {% for error in form.title.errors or form.text.errors %}
                <p class="error-class">{{ error }}</p>
            {% endfor %}
        </div>
    </form>
</div>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Index page</h1>
{% endblock %}

core/templates/login.html
{% extends 'base.html' %}
{% from "_render_field.html" import render_field %}

{% block content %}
    <div class="form-div justify-content-center col-md-4">
        <form method="POST">
            <div class="form-group">
                <div class="form-group row">
                    <h4>Log-in To Your Account</h4>
                </div>
                    {{ form.hidden_tag() }}
                <div class="form-group row">
                    {{ render_field(form.email, class='form-control') }}
                </div>
                <div class="form-group row">
                    {{ render_field(form.password, class='form-control') }}
                </div>
                <div class="form-group row">
                    {{ form.submit(class='btn-customized btn btn-success') }}
                </div>
            </div>
        </form>
    </div>
{% endblock %}

core/templates/permit.html
{% extends 'base.html' %}

{% block content %}
    <h3>{{ permit.title }}</h3>
    <h3>{{ permit.text }}</h3>
    <p>{{ permit.date.strftime('%d-%m-%Y') }}</p>
    <p>{{ permit.author.username }}</p>
    <p>{{ permit.location | upper }}</p>
    <p>{{ permit.mileage | round(2) }}</p>
    <p>{{ permit.resolved | capitalize }}</p>
    <p>{{ permit.follow_up | capitalize }}</p>

<div>
    {% if permit.author == current_user %}
        <a href="{{ url_for('permit.update_permit', permit_id = permit.id) }}">Update</a>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal">Delete</button>
    {% endif %}
</div>
<div class="modal" tabindex="-1" id="deleteModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{{ permit.title }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>You sure You want to permanently delete Permit?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <form action="{{ url_for('permit.delete_permit', permit_id = permit.id) }}">
            <input type="submit" class="btn btn-danger" value="Confirm Delete" />
          </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

core/templates/permit_list.html
{% extends 'base.html' %}

{% block content %}
    {% if permits.items %}
        {% for p in permits.items %}
        <div class="form-div justify-content-center col-md-12">
            <div class="row">
                <div class="col-md-11">
                    <h3>{{ p.title }}</h3>
                    <p><small>Submitted on {{ p.date.strftime('%d/%m/%Y') }} by
                    <a class="link-dark" href="{{ url_for('accounts.user_permits', username=p.author.username) }}">
                        {{ p.author.username | capitalize }}
                    </a>
                    </small></p>
                    <p>{{ p.text|truncate(180) }}...
                        <a class="link-light" href="{{ url_for('permit.permit', permit_id=p.id) }}">Read more</a>
                    </p>
                </div>
                <div class="col-md-1 my-auto align-self-center">
                    {% if p.author == current_user %}
                        <button class="">
                            <a class="link-light" href="{{ url_for('permit.update_permit', permit_id = p.id) }}">Update</a>
                        </button>
                        <hr>
                        <button type="button" class="" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    {% endif %}
                </div>

                <div class="modal" tabindex="-1" id="deleteModal">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title">{{ p.title }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <p>You sure You want to permanently delete Permit?</p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                          <form action="{{ url_for('permit.delete_permit', permit_id = p.id) }}">
                            <input type="submit" class="btn btn-danger" value="Confirm Delete" />
                          </form>
                      </div>
                    </div>
                  </div>
                </div>

            </div>
        </div>
        {% endfor %}
    {% else %}
        <h3 class="main-theme d-flex justify-content-center">No submitted forms yet</h3>
    {% endif %}


{% endblock %}

core/templates/register.html
{% extends 'base.html' %}
{% from "_render_field.html" import render_field %}

{% block content %}
    <div class="form-div justify-content-center col-md-4">
        <form method="POST">
            <div class="form-group">
                <div class="form-group row">
                    <h4>Register Your Account</h4>
                </div>
                {{ form.hidden_tag() }}
                <div class="form-group row">
                    {{ render_field(form.email, class='form-control') }}
                </div>
                <div class="form-group row">
                    {{ render_field(form.username, class='form-control') }}
                </div>
                <div class="form-group row">
                    {{ render_field(form.password, class='form-control') }}
                </div>
                <div class="form-group row">
                    {{ render_field(form.pass_confirm, class='form-control') }}
                </div>
                <div class="form-group row">
                    {{ form.submit(class='btn-customized btn btn-success') }}
                </div>
            </div>
        </form>
    </div>
{% endblock %}

core/templates/update.html
{% extends "base.html" %}
{% from "_render_field.html" import render_field %}

{% block content %}
    <div class="form-div justify-content-center col-md-4">
        <form  method="POST">
            <div class="form-group">
                <div class="form-group row">
                    <h4>Profile of {{ current_user.username | capitalize }}</h4>
                </div>
                <div class="form-group row">
                    {{ render_field(form.username, class='form-control') }}
                </div>
                <div class="form-group row">
                    {{ render_field(form.email, class='form-control') }}
                </div>
                <div class="form-group row">
                    {{ form.submit(class="btn-customized btn btn-primary") }}
                </div>
            </div>
        </form>
    </div>
{% endblock %}

core/templates/user_permits.html
{% extends 'base.html' %}

{% block content %}
<h1>Profile of {{ user.username }}</h1>

{% for p in permits.items %}
    <a href="{{ url_for('permit.permit', permit_id = p.id) }}">{{ p.title }}</a>
    <a href="{{ url_for('accounts.user_permits', username=p.author.username) }}">Author: {{ p.author.username }}</a>
    <p>Published on: {{ p.date.strftime('%d-%m-%Y') }}</p>
    <p>{{ p.text }}</p>
{% endfor %}
<ul>
    {% for page_num in permits.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if permits.page == page_num %}
            <li class="disabled">
                <a href="{{ url_for('accounts.user_permits', username=user.username, page=page_num) }}">{{ page_num }}</a>
            </li>
        {% else %}
            <li>
                <a href="{{ url_for('accounts.user_permits', username=user.username, page=page_num) }}">{{ page_num }}</a>
            </li>
        {% endif %}
    {% endfor %}
</ul>

{% endblock %}